
    fastcgi_hide_header X-Powered-By;
    fastcgi_hide_header X-Runtime;
    fastcgi_hide_header X-Version;
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;