server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;


    # 单独配置上传文件的访问路径
    location /uploads/ {
        alias /data/uploads/;
        autoindex off;  # 禁止目录浏览
        add_header Cache-Control "public, max-age=31536000";  # 长期缓存
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 启用 gzip 压缩
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 缓存静态资源
    location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 1d;
    }

    # 错误页面
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
